services:
  - type: web
    name: growstro-backend
    runtime: docker
    plan: free
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:1KLXrP8swE8s330S2U0YJLsdP0AMaELoSSzUeizj3Js=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: growstro-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: growstro-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: growstro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: growstro-db
          property: password

databases:
  - name: growstro-db
    plan: free
